repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: debug-statements

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
  - id: ruff

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  -  id: bandit
     args: [--skip, "B101"]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.27.2
  hooks:
  - id: gitleaks

- repo: https://github.com/python-poetry/poetry
  rev: 2.1.3
  hooks:
  -   id: poetry-check
