site_name: Otary
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo-bg-transparent.png
  favicon: img/logo-bg-transparent.png
  language: en

repo_name: poupeaua/otary
repo_url: https://github.com/poupeaua/otary

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home:
    - index.md
    - Why Otary?: why.md
    - Quickstart: quickstart.md
    - Installation: installation.md
    - PyPI Releases: https://pypi.org/project/otary

  - API:
      - api/index.md
      - Image: # -------------------------------- IMAGE -------------------------------
        - api/image/index.md

        - I/O:
          - api/image/io/index.md
          - Reader: api/image/io/reader.md
          - Writer: api/image/io/writer.md

        - Properties: api/image/properties.md
        - Conversion: api/image/conversion.md

        - Analysis:
          - api/image/analysis/index.md
          - Scoring: api/image/analysis/scoring.md

        - Transformers:
          - api/image/transformers/index.md
          - Cropping: api/image/transformers/cropping.md
          - Geometry: api/image/transformers/geometry.md
          - Morphology: api/image/transformers/morphology.md
          - Binarization & Thresholding: api/image/transformers/thresholding.md

        - Drawer:
          - api/image/drawer/index.md
          - Drawing: api/image/drawer/drawing.md
          - Renderers: api/image/drawer/renderers.md

      - Geometry: # ---------------------------- GEOMETRY -----------------------------
        - api/geometry/index.md

        - Discrete:
          - api/geometry/discrete/point.md

          - Shape:
            - Polygon: api/geometry/discrete/shape/polygon.md
            - Rectangle: api/geometry/discrete/shape/rectangle.md
            - Triangle: api/geometry/discrete/shape/triangle.md

          - Linear:
            - Segment: api/geometry/discrete/linear/segment.md
            - Linear Spline: api/geometry/discrete/linear/linear_spline.md

            - Directed:
              - Vector: api/geometry/discrete/linear/directed/vector.md
              - Vectorized Linear Spline: api/geometry/discrete/linear/directed/vectorized_linear_spline.md

        - Continuous:
          - Circle: api/geometry/continuous/circle.md
          - Ellipse: api/geometry/continuous/ellipse.md

  - Learn:
    - learn/index.md

  - About:
    - about/history.md
    - A Fair Advice: about/fair_advice.md
    - Contributing: about/contributing.md
    - License: about/license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/poupeaua/otary
      name: GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/otary
      name: PyPI

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
