name: docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec
        with:
          poetry-version: "2.4.1"

      - name: 🚀 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          poetry config virtualenvs.create false
          poetry install --only docs

      - name: ✅ Deploy Docs on gh-pages
        run: |
          make docs-deploy
