name: static-check

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - master
      - release

permissions:
  contents: read

jobs:

  static-check:

    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "2.1.3"

      - name: 🚀 Install Dependencies
        run: |
          # libgl1 library install needed for opencv-python to be imported to work
          sudo apt-get update -y
          sudo apt-get install libgl1 -y
          python -m pip install --upgrade pip
          poetry config virtualenvs.create false
          poetry install --without docs,dev,test

      - name: ✅ Check Code Quality - Pylint
        run: |
          make check-pylint
        continue-on-error: false

      - name: ✅ Check Code Quality - Ruff
        run: |
          make check-ruff
        continue-on-error: false

      - name: ✅ Check Code Quality - Mypy
        run: |
          make check-mypy
        continue-on-error: false

      - name: ✅ Check Code Quality - Ty
        run: |
          echo "\n----------------------------"
          echo "Checking typing quality - Ty"
          echo "----------------------------"
          PYTHON_PATH=$(poetry env info | grep '^Path:' | tail -n1 | sed 's/^Path:[[:space:]]*//')
          ty check --python=$PYTHON_PATH otary/
        continue-on-error: false

      - name: ✅ Check Code Quality - Black
        run: |
          make check-black
        continue-on-error: false
  