name: test

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - master
      - release

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "2.1.3"

      - name: 🚀 Install Dependencies
        run: |
          # libgl1 library install needed for opencv-python to be imported to work
          sudo apt-get update -y
          sudo apt-get install libgl1 -y
          python -m pip install --upgrade pip
          poetry config virtualenvs.create false
          poetry install --without docs

      - name: ✅ Check Code Quality - Pylint
        run: |
          make check-pylint
        continue-on-error: false

      - name: ✅ Check Code Quality - Ruff
        run: |
          make check-ruff
        continue-on-error: false

      - name: ✅ Check Code Quality - Mypy
        run: |
          make check-mypy
        continue-on-error: false

      - name: ✅ Check Code Quality - Black
        run: |
          make check-black
        continue-on-error: false


  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "2.1.3"

      - name: 🚀 Install Dependencies
        run: |
          # libgl1 library install needed for opencv-python to be imported to work
          sudo apt-get update -y
          sudo apt-get install libgl1 -y
          python -m pip install --upgrade pip
          poetry config virtualenvs.create false
          poetry install --without docs

      - run: mkdir coverage

      - name: ✅ Run Tests
        run: make test
        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage
          include-hidden-files: true

      - name: Upload Coverage
        if: ${{ matrix.python-version == '3.13' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
