name: test

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - master
      - release

permissions:
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
      fail-fast: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec
        with:
          poetry-version: "2.4.1"

      - name: 🚀 Install Dependencies
        run: |
          # libgl1 library install needed for opencv-python to be imported to work
          sudo apt-get update -y
          sudo apt-get install libgl1 -y
          python -m pip install --upgrade pip
          poetry config virtualenvs.create false
          poetry install --without docs,dev,check

      - run: mkdir coverage

      - name: ✅ Run Tests
        run: make test
        env:
          COVERAGE_FILE: coverage/.coverage.${{ runner.os }}-py${{ matrix.python-version }}
          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage
          include-hidden-files: true

      - name: Upload Coverage
        if: ${{ matrix.python-version == '3.13' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
